services:
  # Backend Service
  - type: web
    name: resume-parser-backend
    runtime: python
    repo: https://github.com/hetvisoni7/resume-parser
    branch: main
    plan: free
    rootDir: backend
    buildCommand: sed -i 's/\r$//' render_build.sh && chmod +x render_build.sh && ./render_build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000


  # Frontend Service
  - type: static
    name: resume-parser-frontend
    repo: https://github.com/hetvisoni7/resume-parser
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
